### ISSUE TITLE
Continuation

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/PsrLogTestDoubles#11]
@gbirke @manicki I am using this library in some of my current work and would like to enhance and modernize it. My first inclination is to fork the repo and continue there. Though transferring this one to my account (https://github.com/JeroenDeDauw) is also an option. Either is fine by me. Wanted to give you a heads up so you are not surprised by a fork, and so that we can perhaps stick to one well maintained repo.

**Comment by manicki** [comment]
Glad to hear @JeroenDeDauw that the library proves to be useful, and that you want to modernize it. Forking is of course okay. I wonder whether you've considered publishing back your improvements as pull requests here?

**Comment by gbirke** [comment]
Yes, please fork it and do pull requests, I'll gladly incorporate them. The infrastructure (PHPUnit, coding style) can really use some TLC.

If you're planning to support psr/log version 2 and version 3, that might introduce a BC break for PHP 7.4, so we'd need to do a 3.0 release.

**Comment by JeroenDeDauw** [comment]
> I wonder whether you've considered publishing back your improvements as pull requests here?

After what happened with Raz, and given the general hostility of some specific people at WMDE, I am not comfortable with that.

I continue to maintain the library at https://github.com/JeroenDeDauw/PsrLogTestDoubles. You can still redirect this repo and/or the packagist package if you so desire. Let me know, since that requires a little coordination.
